apiVersion: apps/v1
kind: Deployment
metadata:
  name: donations-app
  labels:
    app: donations-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: donations-app
  template:
    metadata:
      labels:
        app: donations-app
    spec:
      containers:
        - name: donations-app
          image: donations-app:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: donations-service
spec:
  selector:
    app: donations-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
